services:

  jikan-rest-api:
    build:
      context: jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
    ports:
      - "9001:8000"
    networks:
      - default
    restart: always

  jikan-redis:
    image: redis
    restart: always
